// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ipt0e_NW6jW8JH6yzA_jDDygnGSgPpU',
    appId: '1:752330450569:web:126015a7aaea3ae4054858',
    messagingSenderId: '752330450569',
    projectId: 'taazabazar-cd20d',
    authDomain: 'taazabazar-cd20d.firebaseapp.com',
    storageBucket: 'taazabazar-cd20d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ipt0e_NW6jW8JH6yzA_jDDygnGSgPpU',
    appId: '1:752330450569:android:126015a7aaea3ae4054858',
    messagingSenderId: '752330450569',
    projectId: 'taazabazar-cd20d',
    storageBucket: 'taazabazar-cd20d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ipt0e_NW6jW8JH6yzA_jDDygnGSgPpU',
    appId: '1:752330450569:ios:126015a7aaea3ae4054858',
    messagingSenderId: '752330450569',
    projectId: 'taazabazar-cd20d',
    storageBucket: 'taazabazar-cd20d.firebasestorage.app',
    iosBundleId: 'com.taazabazar.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ipt0e_NW6jW8JH6yzA_jDDygnGSgPpU',
    appId: '1:752330450569:ios:126015a7aaea3ae4054858',
    messagingSenderId: '752330450569',
    projectId: 'taazabazar-cd20d',
    storageBucket: 'taazabazar-cd20d.firebasestorage.app',
    iosBundleId: 'com.taazabazar.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9ipt0e_NW6jW8JH6yzA_jDDygnGSgPpU',
    appId: '1:752330450569:web:126015a7aaea3ae4054858',
    messagingSenderId: '752330450569',
    projectId: 'taazabazar-cd20d',
    authDomain: 'taazabazar-cd20d.firebaseapp.com',
    storageBucket: 'taazabazar-cd20d.firebasestorage.app',
  );
}
